spring.application.name=bootcamp_microservice
server.port=9092

spring.data.mongodb.uri=mongodb://localhost:27017/bootcampMicroservice

spring.data.mongodb.database=bootcampMicroservice

spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.authentication-database=admin  

logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
